[project]
name = "salty-quiver-stuff"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "click>=8.2.1",
    "pandas>=2.3.1",
    "scipy>=1.16.0",
    "ta>=0.11.0",
    "yfinance>=0.2.65",
]
